### PR TITLE
Unpack commits from metadata in changes.sql

### PR DESCRIPTION
**Pull request by philipdalen**
Related issue https://github.com/GoogleCloudPlatform/fourkeys/pull/132

### CODE REVIEW

**Comment by davidstanke** [comment]
FYI, I ran the e2e tests on this PR and those tests still pass. :)

**Review by dinagraves — APPROVED** [review]

**Comment by dinagraves** [comment]
Thank you! This is great!

**Comment by davincike** [comment]
> Related issue https://github.com/GoogleCloudPlatform/fourkeys/pull/132

**Review by Youngdaddyever — APPROVED** [review]

**Review by Youngdaddyever — CHANGES_REQUESTED** [review]
Go

**Pull request merged**
