### PR TITLE
chore: move unit tests & linting to gh actions, closes #162

### LINKED ISSUE #162: Move Unit Tests & Linting to GitHub Actions
Cloud Build is opaque.  Contributors should be able to see their tests running / failing and all the details included.  GitHub Actions has better visibility.

### PR DESCRIPTION
**Pull request by rethab**
This is a rather simple way of doing this. We could also run eg. flake8 manually and then use some fancy GitHub Action to directly annotate files in PRs. Let me know if you want that as well :)

NB: also closes https://github.com/GoogleCloudPlatform/fourkeys/issues/143 ?

### CODE REVIEW

**Comment by rethab** [comment]
@googlebot I signed it!

**Comment by dinagraves** [comment]
Thank you!  This is great!   

Is there a way to add a filter so it only runs when there have been changes to python files?   In the Cloud Build trigger there is a section for "included files" and it looks for the `*.py`, `**/*.py`, `**/**/*.py`.  

This is another benefit to moving to GitHub actions!  Previously, contributors couldn't see the trigger configuration.

**Comment by dinagraves** [comment]
Going to merge this in and try to figure out the filtering afterwards!  Thank you for your contribution!

**Review by dinagraves — APPROVED** [review]

**Comment by rethab** [comment]
Apologies @dinagraves . I was on vacation :) I'll work on this asap

**Comment by rethab** [comment]
here you go: https://github.com/GoogleCloudPlatform/fourkeys/pull/189

**Pull request merged**
