### PR TITLE
Use secretmanager v1 API instead of v1beta1

### PR DESCRIPTION
**Pull request by rlingutla**
Hello!

I am engineer on the Secret Manager product and would like to update the version of the API you are using. V1 contains all of the same features as V1Beta1 is better supported. Let me know if you have any questions. 

Regards, 
Rachana

### CODE REVIEW

**Review by dinagraves — APPROVED** [review]
Thank you, Rachana!

Note: I have run the e2e tests and confirm that this works as expected.

**Comment by rlingutla** [comment]
Thank you for running the tests!

**Pull request merged**
