### PR TITLE
Change grafana connector

### PR DESCRIPTION
**Pull request by fbtravi**
Resolved [Issue](https://github.com/GoogleCloudPlatform/fourkeys/issues/397).
@davidstanke

### CODE REVIEW

**Comment by fbtravi** [comment]
The timezone on the dashboard was defined as UTC, since when a post occurs in the big query in timestamp it converts to UTC.

**Review by davidstanke — CHANGES_REQUESTED** [review]
Hi @fbtravi ! Thanks for this thorough PR. I think it's really close, but I see a few discrepancies between the grafana output using the old connector and the new one. Take a look at these screenshots...

### Old connector
image

### New connector
image

...
Of course, the data are different b/c it's a different run of the data generator. But my concern is about the labels: some of the headings in the middle column are different, and some of the axis labels are different. Can you take a look? Thanks!

**Comment by fbtravi** [comment]
Hi @davidstanke.

Sorry I didn't see the error, but it's fixed.

**Comment by davidstanke** [comment]
Thanks! I think there's one other bit to change, too -- the "Daily Deployments" and "Daily Change Failure Rate" have a y-axis label of "Hours." That doesn't make sense for those graphs. Can we remove those labels?

**Comment by fbtravi** [comment]
HI @davidstanke,

I believe there are no more errors.

**Review by davidstanke — APPROVED** [review]

**Comment by davidstanke** [comment]
Looks great! Thank you @fbtravi for sticking with it. :)

**Pull request merged**
