### PR TITLE
refactor: rename directories with dashes instead of underscores

### LINKED ISSUE #142: Rename files and directories using dashes instead of underscores
We renamed one directory so we could use one variable for the name of the directory and the name of the service in Cloud Run, with Terraform.  You cannot use underscores in Cloud Run service names.   

For consistency, we should rename all the other directories and files to use dashes.

### PR DESCRIPTION
**Pull request by Wyatt-Stanke**
I can't make draft PR's because I don't have GitHub Pro so just pretend that this is a draft. :P
Also, I haven't actually tested running the full application because I can't do e2e tests.

Closes #142

### CODE REVIEW

**Comment by Wyatt-Stanke** [comment]
image
I'm just wondering if I can get this? Is this a Googler/maintainer only thing?

**Comment by Wyatt-Stanke** [comment]
Sheesh--apparently you can't import folders that have dashes in them.

**Comment by davidstanke** [comment]
> I'm just wondering if I can get this? Is this a Googler/maintainer only thing?

Yeah, that can only be triggered by maintainers but I'm hoping to make it a required check for PRs soon.

Now, about this renaming idea... there is some method to the madness. IIRC, Cloud Run services can't use underscores in their names. So they're named with dashes, and we named the folders that contain their source with dashes. But terraform resources can't have dashes. They need underscores. So unfortunately we can't have nice things; there has to be inconsistency between delimiters.

**Comment by Wyatt-Stanke** [comment]
Yeah, sounds like what happens when you bring multiple technologies together. Does that make #142 obsolete?

**Comment by davidstanke** [comment]
> Yeah, sounds like what happens when you bring multiple technologies together. Does that make #142 obsolete?

I'm not sure -- we did rename one and that seemed to work. But we can't change _every_ underscore in the repo to a dash. If you can resolve #142 without breaking other stuff, though, that'd be cool!

**Comment by davidstanke** [comment]
...like, e.g. this isn't going to be happy: `event-handler.publish_to_pubsub = mock.MagicMock(return_value=True)` ...because it's going to try to subtract "handler" from "event"

**Comment by Wyatt-Stanke** [comment]
Restarting in new PR

**Pull request closed without merging**
