### PR TITLE
Update syntax for retrieving event handlers

### PR DESCRIPTION
**Pull request by sbrudz**
Fixes https://github.com/GoogleCloudPlatform/fourkeys/issues/110

### CODE REVIEW

**Review by dinagraves — APPROVED** [review]
Thank you! Once you have the CLA signed, I'll merge this in!

**Comment by dinagraves** [comment]
Hi Steve! Checking in on the CLA.  LMK if you need any help!

-Dina

**Comment by sbrudz** [comment]
Hi Dina,

Our legal department needs to approve the CLA before I can proceed.  Waiting to hear back from them.  My apologies for the delay.

Best regards,

Steve

**Comment by sbrudz** [comment]
@googlebot I signed it!

**Comment by sbrudz** [comment]
@dinagraves Should be all set now.  Thanks for your patience!

**Comment by dinagraves** [comment]
🎉 Thank you for contributing!

**Pull request merged**
