### PR TITLE
Ensure mock data includes incidents

### LINKED ISSUE #51: Ensure at least 1 incident is created with data mocking script
Currently, the script uses random numbers and probability to create incidents.  There should be at minimum one incident for the dashboard.  Otherwise, the dashboard will not display the incident related charts.

### PR DESCRIPTION
**Pull request by davidstanke**
fixes #51 

FYI: as part of this change, I merged `github_data.py` and `gitlab_data.py` into `generate_data.py`, to DRY them out. The resulting file has a few switch statements in it (well, not really, because python doesn't have switch) where the VCSes differ.

I suspect there's a more elegant approach with a more OO design (I don't know the pythonic way, but in Java, I think you'd provide an interface that each VCS would implement). Nonetheless IMHO this is a step forward. :)

### CODE REVIEW

**Comment by dinagraves** [comment]
Awesome! To run the tests locally try following instructions here: https://github.com/GoogleCloudPlatform/fourkeys#running-tests

Right now, the Nox is failing due to Lint errors.

**Comment by davidstanke** [comment]
Lint errors are fixed! (Shame on me for not running the tests locally.)

**Comment by davidstanke** [comment]
@davidstanke : you can simplify by using argparse default values, rather than manually checking for arguments and setting local vars: https://docs.python.org/3/library/argparse.html

**Review by dinagraves — APPROVED** [review]
It works! Will file a bug to refactor more pythonically.

**Comment by dinagraves** [comment]
Also we should have unit tests in a follow-up PR

**Comment by dinagraves** [comment]
Tracking issue filed here: https://github.com/GoogleCloudPlatform/fourkeys/issues/72

**Pull request merged**
