### PR TITLE
Rename INSTALL.md to README.md

### PR DESCRIPTION
**Pull request by dinagraves**
So that it shows up automatically when people look in this directory.

### CODE REVIEW

**Review by davidstanke — APPROVED** [review]
Yup, good call.

**Comment by coryrc** [comment]
Broke the link from this page: https://cloud.google.com/blog/products/devops-sre/using-the-four-keys-to-measure-your-devops-performance

**Comment by dinagraves** [comment]
Thank you for reporting!  I'm going to try to get the blog post updated.  @davidstanke Should we make an empty install.md that redirects to the readme?

**Comment by coryrc** [comment]
If you were going to do the latter, I recommend a symlink

**Comment by davidstanke** [comment]
D'oh! Thank you, @coryrc ! I opened #175 ... w/r/t redirects, my 2c is that we should focus on fixing the blog post instead of adding a symlink or other redirect. My hunch is that that's the only inbound deep link to that page, so I'm reluctant to add a new file just for that one purpose. (I'm optimistically assuming that the blog post can be fixed relatively quickly.)

Anyway, @dinagraves I'll point that issue at you and you can decide. LMK if I can help.

**Comment by dinagraves** [comment]
Thanks, Dave!  I reached out to the editor I worked with -- if it doesn't get updated by EOD tomorrow, I'll add the symlink.

**Comment by dinagraves** [comment]
@coryrc I closed the issue that Dave filed, but I forgot to update here as well.  The link has been fixed on the blog post.  Thank you again for letting us know!

**Pull request merged**
