### PR TITLE
Support EU BigQuery region in terraform setup

### LINKED ISSUE #269: BigQuery Datasource created in EU is not found by Grafana Dashboard
In my deployment I chose `europe-west1` as region and `EU` for data storage.
With that configuration, the Grafana Dashboard complained. that it couldn't find the datasource in `US`.

I fixed it by adding the following line after https://github.com/GoogleCloudPlatform/fourkeys/blob/e9d2525866998f80d2cb28e3e4a21f6f1245e522/dashboard/datasource.yaml#L26
```YAML
processingLocation: EU
```
(as element of `jsonData:`)

Not sure if that is the right approach, but it worked 😉

### PR DESCRIPTION
**Pull request by davidstanke**
Fixes #269 -- in setup, set `event-handler` environment variable for BQ datasource location (it was previously defaulting to US instead of reading from user config)

### CODE REVIEW

**Comment by davidstanke** [comment]
(also includes Flask updates from #275 b/c tests will fail otherwise)

**Comment by dinagraves** [comment]
@davidstanke Looks like this makes the tests fail for some reason? I tried running against this branch and main and main is fine.

**Comment by dinagraves** [comment]
Error: `Resource 'cloud-build-parser' of kind 'SERVICE' in region 'us-central1' in project ... does not exist.`

**Comment by dinagraves** [comment]
Maybe issue is here?  https://github.com/GoogleCloudPlatform/fourkeys/blob/main/e2e_tests_terraform.cloudbuild.yaml#L24

**Comment by davidstanke** [comment]
@dinagraves E2E tests are passing now (we seem to be in a less-flaky phase). Okay to merge this?

**Review by dinagraves — APPROVED** [review]

**Pull request merged**
