### PR TITLE
Multiple repository support on Github

### PR DESCRIPTION
**Pull request by philipdalen**
This PR 
- adds the repository name to the id for "pull_requests" and "issues" events as to prevent conflicts when wanting to push events from multiple repos to one fourkeys instance.
- Added 2 test for the changes
- Fix a few references in the cloudbuild.yaml file (I'm not sure if this is correct though?)

### CODE REVIEW

**Comment by philipdalen** [comment]
@dinagraves just with regards to the changes to the cloudbuild.yaml file, I wanted to test the changes in our live instance so I added a trigger to our cloud build to build the github-parser solution, the changes I made in the .yaml file was what was necessary to make the cloud build work, but I'm not sure if the file was ment to be used in a different way. Would be great to hear what you think.

**Comment by philipdalen** [comment]
@dinagraves also with regards to the test, it might be overkill, just let me know if it is not worth them or if it should be changed.

**Comment by philipdalen** [comment]
@dinagraves I have now fixed the linting issues and removed the changes to the cloudbuild.yaml file but the "nox-pr" still fails and I don't have access to the logs, is there a way to get access to them? Locally when I run the tests it passes.

image

**Review by dinagraves — APPROVED** [review]

**Pull request merged**
